development:
  GOOGLE_CLIENT_ID: <%= ENV["GOOGLE_CLIENT_ID"] %>
  GOOGLE_SECRET_KEY: <%= ENV["GOOGLE_SECRET_KEY"] %>
  

production:
  GOOGLE_CLIENT_ID: <%= ENV["GOOGLE_CLIENT_ID"] %>
  GOOGLE_SECRET_KEY: <%= ENV["GOOGLE_SECRET_KEY"] %>