development:
  GOOGLE_CLIENT_ID: 308710543738-t6dp4sal56ghupflaaud23spm9vqh53h.apps.googleusercontent.com
  GOOGLE_SECRET_KEY: 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
  

production:
  GOOGLE_CLIENT_ID: <%= ENV["GOOGLE_CLIENT_ID"] %>
  GOOGLE_SECRET_KEY: <%= ENV["GOOGLE_SECRET_KEY"] %>